// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuantamAnalytics.Infrastructure.Data;

#nullable disable

namespace QuantamAnalytics.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505102102_AddApplications")]
    partial class AddApplications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at_utc");

                    b.Property<string>("CandidateEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("candidate_email");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("candidate_name");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_profile_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.HasIndex("CandidateProfileId")
                        .HasDatabaseName("ix_applications_candidate_profile_id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_applications_job_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_applications_tenant_id_status");

                    b.HasIndex("TenantId", "JobId", "CandidateProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_applications_tenant_id_job_id_candidate_profile_id");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.CandidateProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("auth_subject");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("full_name");

                    b.Property<string>("Headline")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("headline");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone_number");

                    b.Property<string>("ResumeFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("resume_file_name");

                    b.Property<string>("ResumeObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("resume_object_key");

                    b.Property<DateTimeOffset?>("ResumeUploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resume_uploaded_at_utc");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_candidate_profiles");

                    b.HasIndex("TenantId", "AuthSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_candidate_profiles_tenant_id_auth_subject");

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("ix_candidate_profiles_tenant_id_email");

                    b.ToTable("candidate_profiles", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_published");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("location");

                    b.Property<DateOnly>("PostedOnUtc")
                        .HasColumnType("date")
                        .HasColumnName("posted_on_utc");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("slug");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_jobs_tenant_id_slug");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.Application", b =>
                {
                    b.HasOne("QuantamAnalytics.Domain.Entities.CandidateProfile", null)
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applications_candidate_profiles_candidate_profile_id");

                    b.HasOne("QuantamAnalytics.Domain.Entities.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applications_jobs_job_id");

                    b.HasOne("QuantamAnalytics.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applications_tenants_tenant_id");
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.CandidateProfile", b =>
                {
                    b.HasOne("QuantamAnalytics.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_profiles_tenants_tenant_id");
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.Job", b =>
                {
                    b.HasOne("QuantamAnalytics.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jobs_tenants_tenant_id");
                });
#pragma warning restore 612, 618
        }
    }
}
