// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuantamAnalytics.Infrastructure.Data;

#nullable disable

namespace QuantamAnalytics.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517013514_Phase9And10Baseline")]
    partial class Phase9And10Baseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at_utc");

                    b.Property<string>("CandidateEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("candidate_email");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("candidate_name");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_profile_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.HasIndex("CandidateProfileId")
                        .HasDatabaseName("ix_applications_candidate_profile_id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_applications_job_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_applications_tenant_id_status");

                    b.HasIndex("TenantId", "JobId", "CandidateProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_applications_tenant_id_job_id_candidate_profile_id");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.ApplicationTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_application_tags");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_application_tags_application_id");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_application_tags_tenant_id_name");

                    b.HasIndex("TenantId", "ApplicationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_application_tags_tenant_id_application_id_name");

                    b.ToTable("application_tags", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.ApplicationTimelineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorLabel")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("actor_label");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("audience");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_profile_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_application_timeline_events");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_application_timeline_events_application_id");

                    b.HasIndex("CandidateProfileId")
                        .HasDatabaseName("ix_application_timeline_events_candidate_profile_id");

                    b.HasIndex("TenantId", "ApplicationId", "OccurredAtUtc")
                        .HasDatabaseName("ix_application_timeline_events_tenant_id_application_id_occurr");

                    b.HasIndex("TenantId", "CandidateProfileId", "OccurredAtUtc")
                        .HasDatabaseName("ix_application_timeline_events_tenant_id_candidate_profile_id_");

                    b.ToTable("application_timeline_events", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("action");

                    b.Property<string>("AuthSubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("auth_subject");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log_entries");

                    b.HasIndex("TenantId", "RecordedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_log_entries_tenant_id_recorded_at_utc");

                    b.HasIndex("TenantId", "EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_log_entries_tenant_id_entity_type_entity_id");

                    b.ToTable("audit_log_entries", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.BackgroundCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CandidateEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("candidate_email");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("candidate_name");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_profile_id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("PackageSlug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("package_slug");

                    b.Property<string>("ProviderReportId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_report_id");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.Property<string>("RequestedByAuthSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("requested_by_auth_subject");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StatusDetail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("status_detail");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_background_checks");

                    b.HasIndex("CandidateProfileId")
                        .HasDatabaseName("ix_background_checks_candidate_profile_id");

                    b.HasIndex("ProviderReportId")
                        .IsUnique()
                        .HasDatabaseName("ix_background_checks_provider_report_id")
                        .HasFilter("provider_report_id IS NOT NULL");

                    b.HasIndex("TenantId", "Status", "RequestedAtUtc")
                        .HasDatabaseName("ix_background_checks_tenant_id_status_requested_at_utc");

                    b.ToTable("background_checks", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.CandidateProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("auth_subject");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("full_name");

                    b.Property<string>("Headline")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("headline");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone_number");

                    b.Property<string>("ResumeFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("resume_file_name");

                    b.Property<string>("ResumeObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("resume_object_key");

                    b.Property<DateTimeOffset?>("ResumeUploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resume_uploaded_at_utc");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_candidate_profiles");

                    b.HasIndex("TenantId", "AuthSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_candidate_profiles_tenant_id_auth_subject");

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("ix_candidate_profiles_tenant_id_email");

                    b.ToTable("candidate_profiles", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_markdown");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByAuthSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by_auth_subject");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_email_templates");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_email_templates_tenant_id");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_email_templates_tenant_slug_unique");

                    b.ToTable("email_templates", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.EsignDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<string>("CandidateEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("candidate_email");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("candidate_name");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_profile_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("ProviderSubmissionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_submission_id");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at_utc");

                    b.Property<string>("SentByAuthSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sent_by_auth_subject");

                    b.Property<DateTimeOffset?>("SignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_at_utc");

                    b.Property<string>("SigningUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("signing_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<string>("TemplateSlug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("template_slug");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateTimeOffset?>("ViewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("viewed_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_esign_documents");

                    b.HasIndex("CandidateProfileId")
                        .HasDatabaseName("ix_esign_documents_candidate_profile_id");

                    b.HasIndex("ProviderSubmissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_esign_documents_provider_submission_id")
                        .HasFilter("provider_submission_id IS NOT NULL");

                    b.HasIndex("TenantId", "Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_esign_documents_tenant_id_status_created_at_utc");

                    b.ToTable("esign_documents", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.InterviewEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<string>("CandidateEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("candidate_email");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("candidate_name");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalEventId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_event_id");

                    b.Property<string>("InterviewerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("interviewer_name");

                    b.Property<string>("MeetingJoinUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("meeting_join_url");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("ScheduledEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_end_utc");

                    b.Property<DateTimeOffset>("ScheduledStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_interview_events");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ix_interview_events_submission_id");

                    b.HasIndex("TenantId", "SubmissionId")
                        .HasDatabaseName("ix_interview_events_tenant_id_submission_id");

                    b.HasIndex("TenantId", "Status", "ScheduledStartUtc")
                        .HasDatabaseName("ix_interview_events_tenant_id_status_scheduled_start_utc");

                    b.ToTable("interview_events", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.InterviewerAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndTimeUtc")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time_utc");

                    b.Property<string>("InterviewerAuthSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("interviewer_auth_subject");

                    b.Property<TimeOnly>("StartTimeUtc")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_interviewer_availability");

                    b.HasIndex("TenantId", "InterviewerAuthSubject", "DayOfWeek")
                        .HasDatabaseName("ix_interviewer_availability_tenant_subject_day");

                    b.ToTable("interviewer_availability", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("ContractorAuthSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contractor_auth_subject");

                    b.Property<string>("ContractorEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("contractor_email");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("Hours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("hours");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at_utc");

                    b.Property<DateOnly>("PeriodEndUtc")
                        .HasColumnType("date")
                        .HasColumnName("period_end_utc");

                    b.Property<DateOnly>("PeriodStartUtc")
                        .HasColumnType("date")
                        .HasColumnName("period_start_utc");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<string>("ReviewedByAuthSubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reviewed_by_auth_subject");

                    b.Property<string>("ReviewerNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reviewer_note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_invoices_tenant_id_status");

                    b.HasIndex("TenantId", "ContractorAuthSubject", "PeriodStartUtc")
                        .HasDatabaseName("ix_invoices_tenant_id_contractor_auth_subject_period_start_utc");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedByAuthSubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("deleted_by_auth_subject");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_published");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("location");

                    b.Property<DateOnly>("PostedOnUtc")
                        .HasColumnType("date")
                        .HasColumnName("posted_on_utc");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("slug");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("TenantId", "DeletedAtUtc")
                        .HasDatabaseName("ix_jobs_tenant_deleted")
                        .HasFilter("is_deleted = true");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_jobs_tenant_id_slug");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at_utc");

                    b.Property<string>("RecipientAuthSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("recipient_auth_subject");

                    b.Property<string>("TargetUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("target_url");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("TenantId", "RecipientAuthSubject", "CreatedAtUtc")
                        .HasDatabaseName("ix_notifications_tenant_recipient_created");

                    b.HasIndex("TenantId", "RecipientAuthSubject", "ReadAtUtc")
                        .HasDatabaseName("ix_notifications_tenant_recipient_read");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.OfferLetter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<decimal>("BaseAnnualSalary")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("base_annual_salary");

                    b.Property<string>("BodyMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_markdown");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_profile_id");

                    b.Property<string>("CandidateResponseNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("candidate_response_note");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByAuthSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by_auth_subject");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at_utc");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_offer_letters");

                    b.HasIndex("TenantId", "CandidateProfileId")
                        .HasDatabaseName("ix_offer_letters_tenant_candidate");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_offer_letters_tenant_status");

                    b.ToTable("offer_letters", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.OnboardingChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<string>("AssignedByAuthSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("assigned_by_auth_subject");

                    b.Property<string>("CandidateNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("candidate_note");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_profile_id");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("instructions");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("item_type");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<string>("ReviewerNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reviewer_note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_onboarding_checklist_items");

                    b.HasIndex("CandidateProfileId")
                        .HasDatabaseName("ix_onboarding_checklist_items_candidate_profile_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_onboarding_checklist_items_tenant_id_status");

                    b.HasIndex("TenantId", "CandidateProfileId", "AssignedAtUtc")
                        .HasDatabaseName("ix_onboarding_checklist_items_tenant_id_candidate_profile_id_a");

                    b.ToTable("onboarding_checklist_items", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.PlatformApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByAuthSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by_auth_subject");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("key_prefix");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_platform_api_keys");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_platform_api_keys_key_hash");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_platform_api_keys_tenant_active");

                    b.ToTable("platform_api_keys", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.RecruiterApplicationFilterPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByAuthSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by_auth_subject");

                    b.Property<string>("Location")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Search")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("search");

                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<bool>("StuckOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("stuck_only");

                    b.Property<string>("Tag")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tag");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_recruiter_application_filter_presets");

                    b.HasIndex("TenantId", "CreatedByAuthSubject", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_recruiter_application_filter_presets_tenant_id_created_by_a");

                    b.ToTable("recruiter_application_filter_presets", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("CandidateEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("candidate_email");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("candidate_name");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_profile_id");

                    b.Property<string>("ClientCompanyName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("client_company_name");

                    b.Property<DateTimeOffset?>("ClientDecisionAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("client_decision_at_utc");

                    b.Property<string>("ClientDecisionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("client_decision_note");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("PitchSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("pitch_summary");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SubmittedByAuthSubject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("submitted_by_auth_subject");

                    b.Property<DateTimeOffset?>("SubmittedToClientAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_to_client_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_submissions");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_submissions_application_id");

                    b.HasIndex("CandidateProfileId")
                        .HasDatabaseName("ix_submissions_candidate_profile_id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_submissions_job_id");

                    b.HasIndex("TenantId", "ApplicationId")
                        .IsUnique()
                        .HasDatabaseName("ix_submissions_tenant_id_application_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_submissions_tenant_id_status");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.TenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("auth_subject");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_memberships");

                    b.HasIndex("AuthSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_memberships_auth_subject_unique");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_memberships_tenant");

                    b.ToTable("tenant_memberships", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.TenantSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("CurrentPeriodEndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_ends_at_utc");

                    b.Property<int>("IncludedSeats")
                        .HasColumnType("integer")
                        .HasColumnName("included_seats");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("plan_code");

                    b.Property<decimal>("PricePerSeat")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_seat");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("TrialEndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_ends_at_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_tenant_subscriptions");

                    b.HasIndex("StripeSubscriptionId")
                        .HasDatabaseName("ix_tenant_subscriptions_stripe_sub");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_subscriptions_tenant_unique");

                    b.ToTable("tenant_subscriptions", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entry_type");

                    b.Property<decimal>("Hours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("hours");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TimesheetId")
                        .HasColumnType("uuid")
                        .HasColumnName("timesheet_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date")
                        .HasColumnName("work_date");

                    b.HasKey("Id")
                        .HasName("pk_time_entries");

                    b.HasIndex("TimesheetId")
                        .HasDatabaseName("ix_time_entries_timesheet_id");

                    b.HasIndex("TenantId", "WorkDate")
                        .HasDatabaseName("ix_time_entries_tenant_id_work_date");

                    b.HasIndex("TenantId", "TimesheetId", "WorkDate", "EntryType")
                        .IsUnique()
                        .HasDatabaseName("ix_time_entries_tenant_id_timesheet_id_work_date_entry_type");

                    b.ToTable("time_entries", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.Timesheet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContractorAuthSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contractor_auth_subject");

                    b.Property<string>("ContractorEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("contractor_email");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("review_note");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<string>("ReviewedByAuthSubject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reviewed_by_auth_subject");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateOnly>("WeekStartUtc")
                        .HasColumnType("date")
                        .HasColumnName("week_start_utc");

                    b.HasKey("Id")
                        .HasName("pk_timesheets");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_timesheets_tenant_id_status");

                    b.HasIndex("TenantId", "ContractorAuthSubject", "WeekStartUtc")
                        .IsUnique()
                        .HasDatabaseName("ix_timesheets_tenant_id_contractor_auth_subject_week_start_utc");

                    b.ToTable("timesheets", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset?>("LastAttemptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempted_at_utc");

                    b.Property<string>("LastResponseBody")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_response_body");

                    b.Property<int?>("LastResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("last_response_status_code");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_webhook_deliveries");

                    b.HasIndex("Status", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_webhook_deliveries_status_next_attempt");

                    b.HasIndex("TenantId", "CreatedAtUtc")
                        .HasDatabaseName("ix_webhook_deliveries_tenant_created");

                    b.ToTable("webhook_deliveries", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.WebhookSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConsecutiveFailureCount")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failure_count");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByAuthSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by_auth_subject");

                    b.Property<string>("EventTypes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("event_types");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastDeliveryAttemptUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_delivery_attempt_utc");

                    b.Property<DateTimeOffset?>("LastSuccessfulDeliveryUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_delivery_utc");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("secret_hash");

                    b.Property<string>("SecretPrefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("secret_prefix");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("target_url");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_webhook_subscriptions");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_webhook_subscriptions_tenant_active");

                    b.ToTable("webhook_subscriptions", (string)null);
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.Application", b =>
                {
                    b.HasOne("QuantamAnalytics.Domain.Entities.CandidateProfile", null)
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applications_candidate_profiles_candidate_profile_id");

                    b.HasOne("QuantamAnalytics.Domain.Entities.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applications_jobs_job_id");

                    b.HasOne("QuantamAnalytics.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applications_tenants_tenant_id");
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.ApplicationTag", b =>
                {
                    b.HasOne("QuantamAnalytics.Domain.Entities.Application", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_tags_applications_application_id");

                    b.HasOne("QuantamAnalytics.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_tags_tenants_tenant_id");
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.ApplicationTimelineEvent", b =>
                {
                    b.HasOne("QuantamAnalytics.Domain.Entities.Application", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_timeline_events_applications_application_id");

                    b.HasOne("QuantamAnalytics.Domain.Entities.CandidateProfile", null)
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_timeline_events_candidate_profiles_candidate_pr");

                    b.HasOne("QuantamAnalytics.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_timeline_events_tenants_tenant_id");
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.AuditLogEntry", b =>
                {
                    b.HasOne("QuantamAnalytics.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audit_log_entries_tenants_tenant_id");
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.BackgroundCheck", b =>
                {
                    b.HasOne("QuantamAnalytics.Domain.Entities.CandidateProfile", null)
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_background_checks_candidate_profiles_candidate_profile_id");

                    b.HasOne("QuantamAnalytics.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_background_checks_tenants_tenant_id");
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.CandidateProfile", b =>
                {
                    b.HasOne("QuantamAnalytics.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_profiles_tenants_tenant_id");
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.EmailTemplate", b =>
                {
                    b.HasOne("QuantamAnalytics.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_templates_tenants_tenant_id");
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.EsignDocument", b =>
                {
                    b.HasOne("QuantamAnalytics.Domain.Entities.CandidateProfile", null)
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_esign_documents_candidate_profiles_candidate_profile_id");

                    b.HasOne("QuantamAnalytics.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_esign_documents_tenants_tenant_id");
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.InterviewEvent", b =>
                {
                    b.HasOne("QuantamAnalytics.Domain.Entities.Submission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interview_events_submissions_submission_id");

                    b.HasOne("QuantamAnalytics.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interview_events_tenants_tenant_id");
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("QuantamAnalytics.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_tenants_tenant_id");
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.Job", b =>
                {
                    b.HasOne("QuantamAnalytics.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jobs_tenants_tenant_id");
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.OnboardingChecklistItem", b =>
                {
                    b.HasOne("QuantamAnalytics.Domain.Entities.CandidateProfile", null)
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_onboarding_checklist_items_candidate_profiles_candidate_pro");

                    b.HasOne("QuantamAnalytics.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_onboarding_checklist_items_tenants_tenant_id");
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.RecruiterApplicationFilterPreset", b =>
                {
                    b.HasOne("QuantamAnalytics.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recruiter_application_filter_presets_tenants_tenant_id");
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.Submission", b =>
                {
                    b.HasOne("QuantamAnalytics.Domain.Entities.Application", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_applications_application_id");

                    b.HasOne("QuantamAnalytics.Domain.Entities.CandidateProfile", null)
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_candidate_profiles_candidate_profile_id");

                    b.HasOne("QuantamAnalytics.Domain.Entities.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_jobs_job_id");

                    b.HasOne("QuantamAnalytics.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_tenants_tenant_id");
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.TimeEntry", b =>
                {
                    b.HasOne("QuantamAnalytics.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_time_entries_tenants_tenant_id");

                    b.HasOne("QuantamAnalytics.Domain.Entities.Timesheet", null)
                        .WithMany("Entries")
                        .HasForeignKey("TimesheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_time_entries_timesheets_timesheet_id");
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.Timesheet", b =>
                {
                    b.HasOne("QuantamAnalytics.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_timesheets_tenants_tenant_id");
                });

            modelBuilder.Entity("QuantamAnalytics.Domain.Entities.Timesheet", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
